#!/bin/bash
# init-docker.sh - Auto-start Docker daemon for DinD containers
#
# This script is sourced by /etc/profile.d/ to ensure dockerd is running
# regardless of how the container is launched (direct run, entrypoint override, etc.)
#
# It's idempotent - safe to run multiple times, won't restart dockerd if already running
#
# Note: Uses "return 2>/dev/null || exit" idiom to work when both sourced and executed
# shellcheck disable=SC2317

DOCKER_LOG="/tmp/docker.log"
DAEMON_JSON="/etc/docker/daemon.json"

# Generate Docker daemon configuration from environment variables
generate_daemon_json() {
    # Skip if daemon.json already exists and wasn't generated by us
    if [ -f "${DAEMON_JSON}" ] && ! grep -q "Generated by init-docker.sh" "${DAEMON_JSON}" 2>/dev/null; then
        return
    fi

    # Check if user provided full daemon.json override
    if [ -n "${DOCKER_DAEMON_JSON}" ]; then
        echo "${DOCKER_DAEMON_JSON}" > "${DAEMON_JSON}"
        return
    fi

    # Start with base configuration
    local storage_driver="${DOCKER_STORAGE_DRIVER:-overlay2}"
    local buildkit_enabled="${DOCKER_BUILDKIT_ENABLED:-true}"

    # Build JSON using jq for proper formatting
    local config="{}"
    config=$(echo "$config" | jq --arg sd "$storage_driver" '. + {"storage-driver": $sd}')

    # Add BuildKit feature
    if [ "$buildkit_enabled" = "true" ]; then
        config=$(echo "$config" | jq '. + {"features": {"buildkit": true}}')
    fi

    # Add registry mirrors if specified
    if [ -n "${DOCKER_REGISTRY_MIRRORS}" ]; then
        local mirrors_json
        mirrors_json=$(echo "${DOCKER_REGISTRY_MIRRORS}" | jq -R 'split(",") | map(gsub("^\\s+|\\s+$";""))')
        config=$(echo "$config" | jq --argjson mirrors "$mirrors_json" '. + {"registry-mirrors": $mirrors}')
    fi

    # Add insecure registries if specified
    if [ -n "${DOCKER_INSECURE_REGISTRIES}" ]; then
        local insecure_json
        insecure_json=$(echo "${DOCKER_INSECURE_REGISTRIES}" | jq -R 'split(",") | map(gsub("^\\s+|\\s+$";""))')
        config=$(echo "$config" | jq --argjson insecure "$insecure_json" '. + {"insecure-registries": $insecure}')
    fi

    # Write generated configuration
    echo "$config" > "${DAEMON_JSON}"
}

# Only proceed if running as root
if [ "$(id -u)" -ne 0 ]; then
    return 0 2>/dev/null || exit 0
fi

# Only proceed if dockerd is not already running
if pgrep -x dockerd >/dev/null 2>&1; then
    return 0 2>/dev/null || exit 0
fi

# Generate daemon configuration if needed
generate_daemon_json

# Start dockerd in background
dockerd \
    --host=unix:///var/run/docker.sock \
    --host=tcp://0.0.0.0:2375 \
    > "$DOCKER_LOG" 2>&1 &

# Wait for Docker to be ready (with timeout)
timeout=30
while ! docker info >/dev/null 2>&1; do
    sleep 1
    timeout=$((timeout - 1))
    if [ $timeout -le 0 ]; then
        echo "WARNING: Docker daemon failed to start within 30 seconds" >&2
        return 1 2>/dev/null || exit 1
    fi
done
